-- ============================================================================
-- Script de creation de la base de donnees ZITOUNA (Version COMPLETE & RESTAUREE)
-- ============================================================================

-- 1. NETTOYAGE
BEGIN
    FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN ('FINANCE', 'PRODUCTION', 'STOCK', 'CLIENT', 'MACHINE')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    FOR r IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN ('FINANCE_SEQ', 'SEQ_PRODUCTION', 'SEQ_STOCK', 'SEQ_CLIENT', 'SEQ_MACHINE')) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || r.sequence_name;
    END LOOP;
END;
/

-- 2. SEQUENCES
CREATE SEQUENCE SEQ_CLIENT START WITH 1;
CREATE SEQUENCE SEQ_STOCK START WITH 1;
CREATE SEQUENCE SEQ_MACHINE START WITH 1;
CREATE SEQUENCE SEQ_PRODUCTION START WITH 1;
CREATE SEQUENCE FINANCE_SEQ START WITH 1;

-- 3. TABLES
CREATE TABLE CLIENT (
    ID_CLIENT               NUMBER PRIMARY KEY,
    NOM                     VARCHAR2(100) NOT NULL,
    PRENOM                  VARCHAR2(100) NOT NULL,
    TELEPHONE               VARCHAR2(20),
    ADRESSE                 VARCHAR2(200),
    EMAIL                   VARCHAR2(150),
    TYPE_CLIENT             VARCHAR2(50) DEFAULT 'Particulier',
    TOTAL_OLIVES_LIVREES    NUMBER(10,2) DEFAULT 0,
    DATE_CREATION           DATE DEFAULT SYSDATE,
    STATUT                  VARCHAR2(50) DEFAULT 'Standard'
);

CREATE TABLE STOCK (
    ID_STOCK                    NUMBER PRIMARY KEY,
    TYPE_HUILE                  VARCHAR2(100) NOT NULL,
    QUANTITE_ACTUELLE           NUMBER(10,2) DEFAULT 0,
    SEUIL_ALERTE                NUMBER(10) DEFAULT 50,
    DATE_DERNIERE_MISE_A_JOUR   DATE DEFAULT SYSDATE,
    EMPLACEMENT_STOCKAGE        VARCHAR2(100),
    ETAT_STOCK                  VARCHAR2(50) DEFAULT 'Disponible'
);

CREATE TABLE MACHINE (
    ID_MACHINE                  NUMBER PRIMARY KEY,
    NOM_MACHINE                 VARCHAR2(100) NOT NULL,
    TYPE_MACHINE                VARCHAR2(50) DEFAULT 'Presse',
    ETAT_MARCHE                 VARCHAR2(10) DEFAULT 'OFF',
    TEMPERATURE_ACTUELLE        NUMBER(5,2) DEFAULT 0,
    NIVEAU_CHARGE               NUMBER(5,2) DEFAULT 0,
    ETAT_FONCTIONNEMENT         VARCHAR2(50) DEFAULT 'Normal',
    TYPE_ALERTE                 VARCHAR2(50) DEFAULT 'Aucune',
    NIVEAU_CRITICITE            VARCHAR2(50) DEFAULT 'Faible',
    DATE_DERNIERE_MAINTENANCE   DATE DEFAULT SYSDATE,
    DATE_INSTALLATION           DATE DEFAULT SYSDATE,
    SCORE_SANTE                 NUMBER(3) DEFAULT 100,
    DATE_MISE_A_JOUR            TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE PRODUCTION (
    IDPRODUCTION            NUMBER PRIMARY KEY,
    ID_CLIENT               NUMBER,
    ID_MACHINE              NUMBER,
    ID_STOCK                NUMBER,
    DATEPRODUCTION          DATE DEFAULT SYSDATE,
    QUANTITEOLIVESKG        NUMBER(10) DEFAULT 0,
    TYPEPRESSAGE            VARCHAR2(100),
    STATUT                  VARCHAR2(50) DEFAULT 'En attente',
    HUILEPRODUITEL          NUMBER(10,2) DEFAULT 0,
    RENDEMENT               NUMBER(5,2) DEFAULT 0,
    CONSTRAINT FK_PROD_STOCK FOREIGN KEY (ID_STOCK) REFERENCES STOCK(ID_STOCK),
    CONSTRAINT FK_PROD_MACHINE FOREIGN KEY (ID_MACHINE) REFERENCES MACHINE(ID_MACHINE)
);

CREATE TABLE FINANCE (
    ID_TRANSACTION  NUMBER PRIMARY KEY,
    ID_MACHINE      NUMBER,
    IDPRODUCTION    NUMBER,
    CTYPE           VARCHAR2(255),
    CATEGORIE       VARCHAR2(255),
    MONTANT         NUMBER(10,2),
    DATE_TRANS      DATE DEFAULT SYSDATE,
    DESCRIPTION     CLOB
);

-- 4. TRIGGERS
CREATE OR REPLACE TRIGGER TRG_FINANCE_ID BEFORE INSERT ON FINANCE FOR EACH ROW
BEGIN IF :NEW.ID_TRANSACTION IS NULL THEN SELECT FINANCE_SEQ.NEXTVAL INTO :NEW.ID_TRANSACTION FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_CLIENT_ID BEFORE INSERT ON CLIENT FOR EACH ROW
BEGIN IF :NEW.ID_CLIENT IS NULL THEN SELECT SEQ_CLIENT.NEXTVAL INTO :NEW.ID_CLIENT FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_STOCK_ID BEFORE INSERT ON STOCK FOR EACH ROW
BEGIN IF :NEW.ID_STOCK IS NULL THEN SELECT SEQ_STOCK.NEXTVAL INTO :NEW.ID_STOCK FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_MACHINE_ID BEFORE INSERT ON MACHINE FOR EACH ROW
BEGIN IF :NEW.ID_MACHINE IS NULL THEN SELECT SEQ_MACHINE.NEXTVAL INTO :NEW.ID_MACHINE FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_PRODUCTION_ID BEFORE INSERT ON PRODUCTION FOR EACH ROW
BEGIN IF :NEW.IDPRODUCTION IS NULL THEN SELECT SEQ_PRODUCTION.NEXTVAL INTO :NEW.IDPRODUCTION FROM DUAL; END IF; END;
/

-- 5. DONNEES DE TEST
INSERT INTO MACHINE (ID_MACHINE, NOM_MACHINE) VALUES (SEQ_MACHINE.NEXTVAL, 'Presse Principale');
INSERT INTO CLIENT (ID_CLIENT, NOM, PRENOM) VALUES (SEQ_CLIENT.NEXTVAL, 'Ben Ali', 'Mohamed');
COMMIT;

-- 6. VERIFICATION
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;
