-- PressIQ — Offline Password Reset Requests
-- Run as Oracle user: ZITOUNA

CREATE SEQUENCE SEQ_PWD_RESET START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE PASSWORD_RESET_REQUESTS (
    REQUEST_ID       NUMBER PRIMARY KEY,
    USER_ID          NUMBER,
    USERNAME         VARCHAR2(100) NOT NULL,
    EMAIL            VARCHAR2(150),
    MESSAGE          VARCHAR2(500),
    REQUEST_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    STATUS           VARCHAR2(20) DEFAULT 'PENDING',
    RESOLVED_BY      VARCHAR2(100),
    RESOLVED_TIME    TIMESTAMP,
    NEW_PASSWORD_SET NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_PWDRESET_EMP FOREIGN KEY (USER_ID)
        REFERENCES EMPLOYEES(USER_ID) ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER PWD_RESET_BI
BEFORE INSERT ON PASSWORD_RESET_REQUESTS
FOR EACH ROW
BEGIN
    SELECT SEQ_PWD_RESET.NEXTVAL INTO :NEW.REQUEST_ID FROM DUAL;
END;
/
