-- Auto-fix: clean and repair Arduino STOCK integration (Oracle)
-- Safe to re-run (idempotent where possible)

-- 1) Ensure required columns exist.
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'SOURCE_DONNEE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD SOURCE_DONNEE VARCHAR2(30) DEFAULT ''MANUEL'' NOT NULL';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_STATUS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD ARDUINO_STATUS VARCHAR2(30)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_STOCK_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD ARDUINO_STOCK_ID NUMBER';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_PORT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD ARDUINO_PORT VARCHAR2(30)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_DERNIERE_LECTURE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD ARDUINO_DERNIERE_LECTURE DATE';
    END IF;
END;
/

-- 2) Normalize data before constraints.
UPDATE STOCK
SET SOURCE_DONNEE = 'ARDUINO'
WHERE TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(SOURCE_DONNEE, 'MANUEL') <> 'ARDUINO';

UPDATE STOCK
SET ARDUINO_STATUS = 'REMPLISSAGE'
WHERE TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO'
  AND (ARDUINO_STATUS IS NULL OR ARDUINO_STATUS NOT IN ('REMPLISSAGE', 'STABLE', 'FAIBLE', 'VALIDATED', 'FAIBLE_CONFIRMED'));

UPDATE STOCK
SET ARDUINO_PORT = 'N/A'
WHERE TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO'
  AND (ARDUINO_PORT IS NULL OR TRIM(ARDUINO_PORT) = '');

UPDATE STOCK
SET ARDUINO_DERNIERE_LECTURE = NVL(ARDUINO_DERNIERE_LECTURE, SYSDATE),
    DATE_DERNIERE_MISE_A_JOUR = NVL(DATE_DERNIERE_MISE_A_JOUR, SYSDATE),
    SEUIL_ALERTE = NVL(SEUIL_ALERTE, 5),
    EMPLACEMENT_STOCKAGE = NVL(EMPLACEMENT_STOCKAGE, 'CUVE ARDUINO')
WHERE TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO';

-- 3) Keep only one canonical Arduino row (the latest by ID_STOCK).
DELETE FROM STOCK s
WHERE s.TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(s.SOURCE_DONNEE, 'MANUEL') = 'ARDUINO'
  AND s.ID_STOCK NOT IN (
      SELECT MAX(ID_STOCK)
      FROM STOCK
      WHERE TYPE_HUILE = 'MESURE_ARDUINO'
        AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO'
  );

-- 4) Ensure canonical row exists.
MERGE INTO STOCK s
USING (SELECT 1 AS K FROM DUAL) x
ON (s.TYPE_HUILE = 'MESURE_ARDUINO' AND s.SOURCE_DONNEE = 'ARDUINO')
WHEN MATCHED THEN
    UPDATE SET
        s.SEUIL_ALERTE = 5,
        s.EMPLACEMENT_STOCKAGE = 'CUVE ARDUINO',
        s.ARDUINO_STATUS = NVL(s.ARDUINO_STATUS, 'REMPLISSAGE'),
        s.ARDUINO_PORT = NVL(s.ARDUINO_PORT, 'N/A'),
        s.ARDUINO_DERNIERE_LECTURE = NVL(s.ARDUINO_DERNIERE_LECTURE, SYSDATE),
        s.ETAT_STOCK = CASE
            WHEN s.ARDUINO_STATUS IN ('FAIBLE', 'FAIBLE_CONFIRMED') THEN 'Faible'
            WHEN s.ARDUINO_STATUS = 'VALIDATED' THEN 'Disponible'
            ELSE NVL(s.ETAT_STOCK, 'En commande')
        END
WHEN NOT MATCHED THEN
    INSERT (ID_STOCK, TYPE_HUILE, QUANTITE_ACTUELLE, SEUIL_ALERTE, DATE_DERNIERE_MISE_A_JOUR,
            EMPLACEMENT_STOCKAGE, ETAT_STOCK, SOURCE_DONNEE,
            ARDUINO_STATUS, ARDUINO_STOCK_ID, ARDUINO_PORT, ARDUINO_DERNIERE_LECTURE)
    VALUES (SEQ_STOCK.NEXTVAL, 'MESURE_ARDUINO', 0, 5, SYSDATE,
            'CUVE ARDUINO', 'En commande', 'ARDUINO',
            'REMPLISSAGE', NULL, 'N/A', SYSDATE);

-- 5) Add constraints safely.
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'STOCK' AND CONSTRAINT_NAME = 'CHK_STOCK_SOURCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD CONSTRAINT CHK_STOCK_SOURCE CHECK (SOURCE_DONNEE IN (''MANUEL'', ''ARDUINO''))';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'STOCK' AND CONSTRAINT_NAME = 'CHK_STOCK_ARDUINO_STATUS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD CONSTRAINT CHK_STOCK_ARDUINO_STATUS CHECK (ARDUINO_STATUS IS NULL OR ARDUINO_STATUS IN (''REMPLISSAGE'', ''STABLE'', ''FAIBLE'', ''VALIDATED'', ''FAIBLE_CONFIRMED''))';
    END IF;
END;
/

-- 6) Create indexes safely.
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_STOCK_SOURCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_STOCK_SOURCE ON STOCK(SOURCE_DONNEE)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_STOCK_ARDUINO_STATUS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_STOCK_ARDUINO_STATUS ON STOCK(ARDUINO_STATUS)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'UQ_STOCK_ARDUINO_ROW';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[CREATE UNIQUE INDEX UQ_STOCK_ARDUINO_ROW ON STOCK (
            CASE WHEN TYPE_HUILE = ''MESURE_ARDUINO'' AND SOURCE_DONNEE = ''ARDUINO'' THEN 1 ELSE NULL END
        )]';
    END IF;
END;
/

COMMIT;

-- Optional quick snapshot after fix
SELECT ID_STOCK,
       TYPE_HUILE,
       SOURCE_DONNEE,
       QUANTITE_ACTUELLE,
       ETAT_STOCK,
       ARDUINO_STATUS,
       ARDUINO_STOCK_ID,
       ARDUINO_PORT,
       ARDUINO_DERNIERE_LECTURE
FROM STOCK
WHERE TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO';
