-- Migration: clean and harden Arduino telemetry support in STOCK table (Oracle)

-- 1) Add missing columns safely (idempotent).
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'SOURCE_DONNEE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD SOURCE_DONNEE VARCHAR2(30) DEFAULT ''MANUEL'' NOT NULL';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_STATUS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD ARDUINO_STATUS VARCHAR2(30)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_STOCK_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD ARDUINO_STOCK_ID NUMBER';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_PORT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD ARDUINO_PORT VARCHAR2(30)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_DERNIERE_LECTURE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD ARDUINO_DERNIERE_LECTURE DATE';
    END IF;
END;
/

-- 2) Add constraints safely.
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'STOCK' AND CONSTRAINT_NAME = 'CHK_STOCK_SOURCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD CONSTRAINT CHK_STOCK_SOURCE CHECK (SOURCE_DONNEE IN (''MANUEL'', ''ARDUINO''))';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'STOCK' AND CONSTRAINT_NAME = 'CHK_STOCK_ARDUINO_STATUS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE STOCK ADD CONSTRAINT CHK_STOCK_ARDUINO_STATUS CHECK (ARDUINO_STATUS IS NULL OR ARDUINO_STATUS IN (''REMPLISSAGE'', ''STABLE'', ''FAIBLE'', ''VALIDATED'', ''FAIBLE_CONFIRMED''))';
    END IF;
END;
/

-- 3) Create indexes safely.
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_STOCK_SOURCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_STOCK_SOURCE ON STOCK(SOURCE_DONNEE)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_STOCK_ARDUINO_STATUS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_STOCK_ARDUINO_STATUS ON STOCK(ARDUINO_STATUS)';
    END IF;
END;
/

-- 4) Ensure ARDUINO source value is normalized.
UPDATE STOCK
SET SOURCE_DONNEE = 'ARDUINO'
WHERE TYPE_HUILE = 'MESURE_ARDUINO' AND NVL(SOURCE_DONNEE, 'MANUEL') <> 'ARDUINO';

-- 5) Keep only one canonical Arduino row (latest), remove duplicates.
DELETE FROM STOCK s
WHERE s.TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(s.SOURCE_DONNEE, 'MANUEL') = 'ARDUINO'
  AND s.ID_STOCK NOT IN (
      SELECT MAX(ID_STOCK)
      FROM STOCK
      WHERE TYPE_HUILE = 'MESURE_ARDUINO' AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO'
  );

-- 6) Add uniqueness guarantee for canonical Arduino row.
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'UQ_STOCK_ARDUINO_ROW';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[CREATE UNIQUE INDEX UQ_STOCK_ARDUINO_ROW ON STOCK (
            CASE WHEN TYPE_HUILE = ''MESURE_ARDUINO'' AND SOURCE_DONNEE = ''ARDUINO'' THEN 1 ELSE NULL END
        )]';
    END IF;
END;
/

-- 7) Upsert canonical Arduino row.
MERGE INTO STOCK s
USING (SELECT 1 AS K FROM DUAL) x
ON (s.TYPE_HUILE = 'MESURE_ARDUINO' AND s.SOURCE_DONNEE = 'ARDUINO')
WHEN MATCHED THEN
    UPDATE SET
        s.SEUIL_ALERTE = 5,
        s.EMPLACEMENT_STOCKAGE = 'CUVE ARDUINO',
        s.ARDUINO_STATUS = NVL(s.ARDUINO_STATUS, 'REMPLISSAGE'),
        s.ARDUINO_PORT = NVL(s.ARDUINO_PORT, 'N/A'),
        s.ARDUINO_DERNIERE_LECTURE = NVL(s.ARDUINO_DERNIERE_LECTURE, SYSDATE)
WHEN NOT MATCHED THEN
    INSERT (ID_STOCK, TYPE_HUILE, QUANTITE_ACTUELLE, SEUIL_ALERTE, DATE_DERNIERE_MISE_A_JOUR,
            EMPLACEMENT_STOCKAGE, ETAT_STOCK, SOURCE_DONNEE, ARDUINO_STATUS, ARDUINO_STOCK_ID, ARDUINO_PORT, ARDUINO_DERNIERE_LECTURE)
    VALUES (SEQ_STOCK.NEXTVAL, 'MESURE_ARDUINO', 0, 5, SYSDATE,
            'CUVE ARDUINO', 'En commande', 'ARDUINO', 'REMPLISSAGE', NULL, 'N/A', SYSDATE);

COMMIT;
