-- Health check: Arduino STOCK integration (Oracle)
-- Run after stock/sql_migrate_stock_arduino.sql

-- 1) Column presence checks
SELECT 'COL_SOURCE_DONNEE' AS CHECK_NAME,
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END AS STATUS
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'SOURCE_DONNEE'
UNION ALL
SELECT 'COL_ARDUINO_STATUS',
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_STATUS'
UNION ALL
SELECT 'COL_ARDUINO_STOCK_ID',
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_STOCK_ID'
UNION ALL
SELECT 'COL_ARDUINO_PORT',
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_PORT'
UNION ALL
SELECT 'COL_ARDUINO_DERNIERE_LECTURE',
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'STOCK' AND COLUMN_NAME = 'ARDUINO_DERNIERE_LECTURE';

-- 2) Constraint checks
SELECT 'CHK_STOCK_SOURCE' AS CHECK_NAME,
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END AS STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'STOCK' AND CONSTRAINT_NAME = 'CHK_STOCK_SOURCE'
UNION ALL
SELECT 'CHK_STOCK_ARDUINO_STATUS',
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'STOCK' AND CONSTRAINT_NAME = 'CHK_STOCK_ARDUINO_STATUS';

-- 3) Index checks
SELECT 'IDX_STOCK_SOURCE' AS CHECK_NAME,
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END AS STATUS
FROM USER_INDEXES
WHERE TABLE_NAME = 'STOCK' AND INDEX_NAME = 'IDX_STOCK_SOURCE'
UNION ALL
SELECT 'IDX_STOCK_ARDUINO_STATUS',
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END
FROM USER_INDEXES
WHERE TABLE_NAME = 'STOCK' AND INDEX_NAME = 'IDX_STOCK_ARDUINO_STATUS'
UNION ALL
SELECT 'UQ_STOCK_ARDUINO_ROW',
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END
FROM USER_INDEXES
WHERE TABLE_NAME = 'STOCK' AND INDEX_NAME = 'UQ_STOCK_ARDUINO_ROW';

-- 4) Canonical Arduino row uniqueness
SELECT 'ARDUINO_ROW_COUNT' AS CHECK_NAME,
       COUNT(*) AS VALUE,
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'KO' END AS STATUS
FROM STOCK
WHERE TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO';

-- 5) Data quality for canonical row
SELECT ID_STOCK,
       TYPE_HUILE,
       SOURCE_DONNEE,
       QUANTITE_ACTUELLE,
       ETAT_STOCK,
       ARDUINO_STATUS,
       ARDUINO_STOCK_ID,
       ARDUINO_PORT,
       ARDUINO_DERNIERE_LECTURE
FROM STOCK
WHERE TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO';

-- 6) Illegal status values (must return 0 rows)
SELECT ID_STOCK, ARDUINO_STATUS
FROM STOCK
WHERE TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO'
  AND ARDUINO_STATUS IS NOT NULL
  AND ARDUINO_STATUS NOT IN ('REMPLISSAGE', 'STABLE', 'FAIBLE', 'VALIDATED', 'FAIBLE_CONFIRMED');

-- 7) Freshness (minutes since last Arduino read)
SELECT ID_STOCK,
       ROUND((SYSDATE - NVL(ARDUINO_DERNIERE_LECTURE, SYSDATE)) * 24 * 60, 2) AS MINUTES_SINCE_LAST_READ,
       CASE
           WHEN ARDUINO_DERNIERE_LECTURE IS NULL THEN 'KO'
           WHEN (SYSDATE - ARDUINO_DERNIERE_LECTURE) * 24 * 60 <= 5 THEN 'OK'
           ELSE 'WARN'
       END AS STATUS
FROM STOCK
WHERE TYPE_HUILE = 'MESURE_ARDUINO'
  AND NVL(SOURCE_DONNEE, 'MANUEL') = 'ARDUINO';
