-- Run this on existing Oracle schemas to add AI quality columns safely.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'PRODUCTION' AND COLUMN_NAME = 'ACIDITE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTION ADD (ACIDITE NUMBER(4,2))';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'PRODUCTION' AND COLUMN_NAME = 'SCOREQUALITEIA';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTION ADD (SCOREQUALITEIA NUMBER(5,2))';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'PRODUCTION' AND COLUMN_NAME = 'CONFIANCEIA';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTION ADD (CONFIANCEIA NUMBER(5,2))';
    END IF;
END;
/
