ALTER SESSION SET CURRENT_SCHEMA = ZITOUNA;

SELECT USER AS connected_user FROM DUAL;
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS current_schema FROM DUAL;

SELECT COUNT(*) AS emp_count
FROM ZITOUNA.EMPLOYEES;

SELECT USER_ID, USERNAME, EMAIL, ROLE, STATE, CREATED_AT
FROM ZITOUNA.EMPLOYEES
ORDER BY USER_ID DESC;